name: login
main: login\login
version: 1.0.0
api: [3.9.0]
load: STARTUP
author: PocketMine Team
authors: [shoghicp]
description: Prevents people from impersonating an account, requires registration and login when connecting.
website: https://github.com/PocketMine/login
commands:
 login:
  description: "Logs into an account"
  usage: "/login <password>"
  permission: login.command.login
 login:
  description: "logins an account"
  usage: "/login <password>"
  permission: login.command.login
 link:
  description: "Links an account"
  usage: "/link <other account><other password>"
  permission: login.command.link
 unlink:
  description: "Unlinks linked accounts"
  usage: "/unlink"
  permission: login.command.unlink

permissions:
 login:
  default: op
  description: "Allows using everything login has"
  children:
   login.chat:
    description: "Allows using the chat while not being authenticated"
    default: false
   login.move:
    description: "Allows moving while not being authenticated"
    default: false
   login.lastid:
    description: "Allows authenticating using the last id when enabled in the config"
    default: true
   login.command:
    description: "Allows using login commands"
    default: true
    children:
     login.command.login:
      description: "Allows logining an account"
      default: true
     login.command.login:
      description: "Allows logging into an account"
      default: true
     login.command.link:
      description: "Allows linking to another account"
      default: true
     login.command.unlink:
      description: "Allows unlinking an account"
      default: true
