name: Register
main: Register\Register
version: 2.1.3
api: [3.0.0]
load: STARTUP
author: PocketMine Team
authors: [shoghicp]
description: Prevents people from impersonating an account, requires registration and login when connecting.
website: https://github.com/PocketMine/Register
commands:
 login:
  description: "Logs into an account"
  usage: "/login <password>"
  permission: Register.command.login
 register:
  description: "Registers an account"
  usage: "/register <password>"
  permission: Register.command.register
 link:
  description: "Links an account"
  usage: "/link <other account><other password>"
  permission: Register.command.link
 unlink:
  description: "Unlinks linked accounts"
  usage: "/unlink"
  permission: Register.command.unlink

permissions:
 Register:
  default: op
  description: "Allows using everything Register has"
  children:
   Register.chat:
    description: "Allows using the chat while not being authenticated"
    default: false
   Register.move:
    description: "Allows moving while not being authenticated"
    default: false
   Register.lastid:
    description: "Allows authenticating using the last id when enabled in the config"
    default: true
   Register.command:
    description: "Allows using Register commands"
    default: true
    children:
     simpleauth.command.register:
      description: "Allows registering an account"
      default: true
     simpleauth.command.login:
      description: "Allows logging into an account"
      default: true
     simpleauth.command.link:
      description: "Allows linking to another account"
      default: true
     simpleauth.command.unlink:
      description: "Allows unlinking an account"
      default: true
